<a href="https://colab.research.google.com/github/nataliacarvalho04/desafios-unimed/blob/main/desafios_dio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/analise_de_dados/Datasets/BC250_2017_Trecho_Energia_L.csv")

In [ ]:
#visualizando as 5 primeira linhas
df.head()

,FID,id_objeto,nome,nomeabrev,geometriaaproximada,emduto,tensaoeletrica,numcircuitos,especie,posicaorelativa,operacional,situacaofisica,id_produtor,id_elementoprodutor,geom
0,BC250_2017_Trecho_Energia_L.1,1,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,18.0,MULTILINESTRING ((-39.202516138 -6.99999999999...
1,BC250_2017_Trecho_Energia_L.2,2,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,14.0,MULTILINESTRING ((-41.99999999999989 -4.583121...
2,BC250_2017_Trecho_Energia_L.3,3,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,17.0,MULTILINESTRING ((-40.49999999999989 -6.108253...
3,BC250_2017_Trecho_Energia_L.4,4,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,11.0,MULTILINESTRING ((-41.759499755 -4.13727475399...
4,BC250_2017_Trecho_Energia_L.5,5,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,28.0,MULTILINESTRING ((-38.641455492 -7.99999999999...

In [ ]:
df = df.rename(columns={"emduto":"enduto"})

In [ ]:
df.head(10)

,FID,id_objeto,nome,nomeabrev,geometriaaproximada,enduto,tensaoeletrica,numcircuitos,especie,posicaorelativa,operacional,situacaofisica,id_produtor,id_elementoprodutor,geom
0,BC250_2017_Trecho_Energia_L.1,1,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,18.0,MULTILINESTRING ((-39.202516138 -6.99999999999...
1,BC250_2017_Trecho_Energia_L.2,2,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,14.0,MULTILINESTRING ((-41.99999999999989 -4.583121...
2,BC250_2017_Trecho_Energia_L.3,3,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,17.0,MULTILINESTRING ((-40.49999999999989 -6.108253...
3,BC250_2017_Trecho_Energia_L.4,4,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,11.0,MULTILINESTRING ((-41.759499755 -4.13727475399...
4,BC250_2017_Trecho_Energia_L.5,5,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,28.0,MULTILINESTRING ((-38.641455492 -7.99999999999...
5,BC250_2017_Trecho_Energia_L.6,6,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,6.0,MULTILINESTRING ((-41.477550816 -6.99999999999...
6,BC250_2017_Trecho_Energia_L.7,7,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,27.0,MULTILINESTRING ((-37.97257509 -7.872928406999...
7,BC250_2017_Trecho_Energia_L.8,8,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,30.0,MULTILINESTRING ((-38.9404605729999 -7.3060111...
8,BC250_2017_Trecho_Energia_L.9,9,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,7.0,MULTILINESTRING ((-40.49999999999989 -5.551175...
9,BC250_2017_Trecho_Energia_L.10,10,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,5.0,MULTILINESTRING ((-40.6348668599999 -5.9198682...

In [ ]:
df.shape
#total de colunas e linhas

(1187, 15)

In [ ]:
df.columns

Index(['FID', 'id_objeto', 'nome', 'nomeabrev', 'geometriaaproximada',
       'enduto', 'tensaoeletrica', 'numcircuitos', 'especie',
       'posicaorelativa', 'operacional', 'situacaofisica', 'id_produtor',
       'id_elementoprodutor', 'geom'],
      dtype='object')

In [ ]:
df.dtypes

FID                     object
id_objeto                int64
nome                    object
nomeabrev               object
geometriaaproximada     object
enduto                  object
tensaoeletrica         float64
numcircuitos           float64
especie                 object
posicaorelativa         object
operacional             object
situacaofisica          object
id_produtor            float64
id_elementoprodutor    float64
geom                    object
dtype: object

In [ ]:
df.tail()
#últimas linhhas

,FID,id_objeto,nome,nomeabrev,geometriaaproximada,enduto,tensaoeletrica,numcircuitos,especie,posicaorelativa,operacional,situacaofisica,id_produtor,id_elementoprodutor,geom
1182,BC250_2017_Trecho_Energia_L.1183,1183,NaN,NaN,NaN,NaN,NaN,NaN,Transmissão,Na superfície,Sim,Construída,250016.0,NaN,MULTILINESTRING ((-38.3878000520585 -11.560233...
1183,BC250_2017_Trecho_Energia_L.1184,1184,NaN,NaN,NaN,NaN,NaN,NaN,Transmissão,Na superfície,Sim,Construída,250016.0,NaN,MULTILINESTRING ((-38.02240865148618 -11.64316...
1184,BC250_2017_Trecho_Energia_L.1185,1185,LT 500 kV OLINDINA /CAMACARI II C-1 BA,NaN,Não,Não,NaN,NaN,Transmissão,Emerso,Sim,Construída,250016.0,1870.0,MULTILINESTRING ((-38.3069981519999 -12.051899...
1185,BC250_2017_Trecho_Energia_L.1186,1186,LT 500 kV P. AFONSO IV /OLINDINA C-1 BA,NaN,Não,Não,NaN,NaN,Transmissão,Emerso,Sim,Construída,250016.0,1885.0,MULTILINESTRING ((-38.38382370972375 -11.31290...
1186,BC250_2017_Trecho_Energia_L.1187,1187,LT 500 kV OLINDINA /CAMACARI II C-2 BA,NaN,Não,Não,NaN,NaN,Transmissão,Emerso,Sim,Construída,250016.0,1869.0,MULTILINESTRING ((-38.37783343506586 -10.99048...

In [ ]:
df.describe()

,id_objeto,tensaoeletrica,numcircuitos,id_produtor,id_elementoprodutor
count,1187.000000,220.000000,0.0,1184.000000,781.000000
mean,594.000000,101.181818,NaN,250003.591216,1401.718310
std,342.801692,151.514315,NaN,4.086155,828.937576
min,1.000000,0.000000,NaN,250000.000000,1.000000
25%,297.500000,0.000000,NaN,250000.000000,216.000000
50%,594.000000,0.000000,NaN,250003.000000,1803.000000
75%,890.500000,230.000000,NaN,250003.000000,1998.000000
max,1187.000000,500.000000,NaN,250016.000000,2195.000000

In [ ]:
df["situacaofisica"].unique()
#trazer os valores unicos dessa coluna

array(['Construída', 'Desconhecida', 'Abandonada', 'Destruída', nan],
      dtype=object)

In [ ]:
#criando uma constante com os valores unicos de imoveis construidos
imoveis_construidos = df.loc[df["situacaofisica"] == "Construída"]
imoveis_construidos.head()

,FID,id_objeto,nome,nomeabrev,geometriaaproximada,enduto,tensaoeletrica,numcircuitos,especie,posicaorelativa,operacional,situacaofisica,id_produtor,id_elementoprodutor,geom
0,BC250_2017_Trecho_Energia_L.1,1,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,18.0,MULTILINESTRING ((-39.202516138 -6.99999999999...
1,BC250_2017_Trecho_Energia_L.2,2,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,14.0,MULTILINESTRING ((-41.99999999999989 -4.583121...
2,BC250_2017_Trecho_Energia_L.3,3,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,17.0,MULTILINESTRING ((-40.49999999999989 -6.108253...
3,BC250_2017_Trecho_Energia_L.4,4,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,11.0,MULTILINESTRING ((-41.759499755 -4.13727475399...
4,BC250_2017_Trecho_Energia_L.5,5,,NaN,Não,Não,NaN,NaN,Desconhecido,Na superfície,Sim,Construída,250010.0,28.0,MULTILINESTRING ((-38.641455492 -7.99999999999...

In [ ]:
imoveis_construidos["situacaofisica"].unique()

array(['Construída'], dtype=object)

In [ ]:
df.groupby("situacaofisica")["posicaorelativa"].nunique()
#quantificação

situacaofisica
Abandonada      1
Construída      6
Desconhecida    2
Destruída       0
Name: posicaorelativa, dtype: int64

In [ ]:
df.groupby("")